# Generated by Django 5.1.4 on 2025-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=128)),
                ("branch_name", models.CharField(max_length=128)),
                ("is_islamic", models.BooleanField(null=True)),
            ],
        ),
    ]
