# Generated by Django 5.1.4 on 2025-03-04 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking_app", "0002_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="first_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="last_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banks",
                to="banking_app.bank",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
