# Generated by Django 5.1.4 on 2025-02-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking_app", "0003_account_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="user",
        ),
    ]
