# Generated by Django 5.1.4 on 2025-03-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking_app", "0003_remove_account_user_name_account_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banks",
                to="banking_app.bank",
            ),
        ),
    ]
