# Generated by Django 5.1.4 on 2025-03-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking_app", "0004_alter_account_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_balance",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banks",
                to="banking_app.bank",
            ),
        ),
    ]
