# Generated by Django 5.1.4 on 2025-03-06 09:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking_app", "0005_alter_account_account_balance_alter_account_bank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("user", "bank")},
        ),
    ]
